name = "myesimplus-com"
main = "src/index.js"
compatibility_date = "2024-12-19"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "myesimplus-com"
[[env.production.kv_namespaces]]
binding = "CONTACTS"
id = "8a0a8a95d05b42a48d3ac798489b6dcc"
[[env.production.kv_namespaces]]
binding = "ANALYTICS"
id = "d8851e821325442eb8640910657dee64"
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "v1"

[env.staging]
name = "myesimplus-com-staging"
[[env.staging.kv_namespaces]]
binding = "CONTACTS"
id = "8a0a8a95d05b42a48d3ac798489b6dcc"
[[env.staging.kv_namespaces]]
binding = "ANALYTICS"
id = "d8851e821325442eb8640910657dee64"
[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "v1"